services:
  backend:
    container_name: backend_seu_cantinho
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend-seu_cantinho
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
    - '3001:3001'
    depends_on:
    - backend

