@startuml

Pessoa <|-- Cliente
Pessoa <|-- Proprietario

Reserva "0..*" -- "1" Cliente : faz
Reserva "1" -- "1" Pagamento : possui
Reserva "1" -- "1" Espaço : contém

Espaço "0..*" -- "1" Proprietario : contém
Endereço "1" -- "1" Espaço : contém
Periodo "1" -- "1" Reserva : contém

Class Pessoa {
  id : unsigned int
  nome: String
  data_nascimento: date
  cpf: String
  email: String
  telefone: String
  
  fazerLogin()
  fazerLogoff()
  atualizarPerfil()
  criarPerfil()
  removerPerfil()
}


Class Endereço {
  rua: String
  numero: int
  bairro: String
  cidade: String
  estado: String
  complemento: String
  
  criaEndereço()
  removeEndereço()
  atualizaEndereço()
}

class Periodo {
  inicio: Instant
  fim: Instant
  
  duracao(): Duration
}

Class Cliente {
  alugueis: List
  
  verificarHistorico()
  solicitaAluguel()
  solicitaCancelamento()
}


Class Proprietario {
  espaços: List
  
  adicionaEspaço()
  removeEspaço()
  atualizaEspaõ()
  solicitaCancelamento()
}


Class Reserva {
  id : unsigned int
  data_reserva: date
  Cliente: Cliente
  espaco_aluguel: Espaço
  pagamento: Pagamento
  status: String
  periodo : Periodo
  
  criaReserva()
  cancelaReserva()
  removeReserva()
  atualizaReserva()
  verificaStatus()
}


Class Pagamento {
  valor_pago: double
  preço: double
  status: String
  
  criaPagamento()
  removePagamento()
  atualizaPagamento()
  processaPagamento()
  estornarPagamento()
}


Class Espaço {
  foto: List<Image>
  capacidade: int
  preço: double
  tipo: String
  endereço: Endereço
  proprietario: Proprietario
  
  criaEspaco()
  removeEspaço()
  atualizaEspaco()
  verificaDisponibilidade()
}

enum StatusReserva {
  PENDENTE
  CONFIRMADA
  EM_ANDAMENTO
  CONCLUIDA
  CANCELADA
}

enum StatusPagamento {
  APROVADO
  RECUSADO
  ESTORNADO
  SINAL
  PENDENTE
}
@enduml
